# Generated by Django 6.0.1 on 2026-01-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_remove_customer_address_customer_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_image_base64",
            field=models.TextField(blank=True, null=True),
        ),
    ]
