# Generated by Django 6.0.1 on 2026-01-13 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0003_rename_deposit_id_transaction_deposite_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="deposite_id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="expense_id",
        ),
        migrations.AddField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="transaction",
            name="deposite_type",
            field=models.CharField(default="other"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.CharField(default=""),
        ),
        migrations.AddField(
            model_name="transaction",
            name="expense_type",
            field=models.CharField(default="other"),
        ),
    ]
