# Generated by Django 6.0.1 on 2026-01-15 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_remove_customer_address_customer_password_and_more"),
        ("transaction", "0004_remove_transaction_deposite_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="customer_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="f_customer_id",
                to="customer.customer",
            ),
        ),
    ]
