# Generated by Django 6.0.1 on 2026-01-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0006_alter_transaction_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="profile_image_base64",
            field=models.TextField(blank=True, null=True),
        ),
    ]
