# Generated by Django 6.0.1 on 2026-01-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0007_transaction_profile_image_base64"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="profile_image_base64",
        ),
    ]
